import { Participant, Scenario } from "@/lib/types";

export type SpotlightTone = "signal" | "balance" | "decision";

export type DemoStep =
  | { type: "message"; participantId: string; text: string; topic: string; delay: number }
  | { type: "spotlight"; delay: number; title: string; note: string; tone: SpotlightTone };

export const participants: Participant[] = [
  { id: "maya", name: "Maya", role: "Product", color: "#63e6d8" },
  { id: "jon", name: "Jon", role: "Engineering", color: "#8db9ff" },
  { id: "sora", name: "Sora", role: "Research", color: "#f1c96a" },
  { id: "lena", name: "Lena", role: "Design", color: "#ff8577" },
];

export const scenarios: Scenario[] = [
  {
    key: "dominant",
    label: "Dominant speaker",
    pulse: "Pressure rises around one voice",
    description: "One participant fills the space until the system opens the circle.",
    script: [
      { participantId: "maya", text: "Okay launch readiness. I've been thinking about this all weekend and I want to walk through where I think we are.", delay: 0, topic: "launch" },
      { participantId: "maya", text: "Marketing has the campaign locked for the 14th. That's a hard date. If we slip past it we lose the whole quarter's positioning.", delay: 2400, topic: "launch" },
      { participantId: "jon", text: "Right but on the infra side we still have the rate limiter issue.", delay: 1800, topic: "infra" },
      { participantId: "maya", text: "I know and I hear you, but I've already told the CMO we're shipping the 14th. We need to figure out what we cut, not whether we ship.", delay: 1200, topic: "launch" },
      { participantId: "maya", text: "My read is we drop the analytics dashboard from v1, ship the core flow, and follow up two weeks later.", delay: 2200, topic: "scope" },
      { participantId: "sora", text: "Did the user research support cutting analytics?", delay: 1600, topic: "analytics" },
      { participantId: "maya", text: "It's not about the research, it's about scope. We can revisit it. The point is we have to make a call today.", delay: 1000, topic: "scope" },
      { participantId: "maya", text: "I'd rather ship something tight than something complete and late.", delay: 2000, topic: "launch" },
      { participantId: "maya", text: "Lena, can design support a cut down version by Friday?", delay: 2400, topic: "scope" },
      { participantId: "lena", text: "Probably yes.", delay: 1400, topic: "scope" },
      { participantId: "maya", text: "Great. So we're aligned. I'll send the updated scope to the team tonight.", delay: 1600, topic: "scope" },
      { participantId: "jon", text: "Wait I don't think we've actually talked about the rate limiter.", delay: 1800, topic: "infra" },
      { participantId: "maya", text: "We can handle that in eng sync. Let me get the scope locked first.", delay: 1200, topic: "scope" },
      { participantId: "sora", text: "And I haven't shared what the research showed about the dashboard.", delay: 1600, topic: "analytics" },
      { participantId: "maya", text: "Sora can we park that for now? I'm trying to get to a decision.", delay: 1000, topic: "decision" },
      { participantId: "maya", text: "Let me also bring up the pricing changes. I think we move to three tiers instead of two.", delay: 2600, topic: "pricing" },
      { participantId: "maya", text: "Starter at twenty, Pro at fifty, Team at one twenty per seat. That's where the analyst report landed.", delay: 2000, topic: "pricing" },
      { participantId: "lena", text: "Has finance signed off on that?", delay: 1800, topic: "pricing" },
      { participantId: "maya", text: "Not yet but they will. The math works out.", delay: 1200, topic: "pricing" },
      { participantId: "maya", text: "And on the support side I want us to commit to twenty four hour response time during launch week.", delay: 2400, topic: "support" },
      { participantId: "jon", text: "Twenty four hours is aggressive given headcount.", delay: 1600, topic: "support" },
      { participantId: "maya", text: "It's a launch week thing. We'll all be on call. I'll personally take overflow.", delay: 1400, topic: "support" },
      { participantId: "maya", text: "Sora can you draft the help docs by Wednesday?", delay: 2200, topic: "support" },
      { participantId: "sora", text: "Wednesday is tight. I'm still wrapping the user interviews.", delay: 1800, topic: "support" },
      { participantId: "maya", text: "Push the interviews to next week. Docs are higher priority right now.", delay: 1200, topic: "support" },
      { participantId: "maya", text: "Okay last thing. I want to talk about the launch event itself.", delay: 2600, topic: "event" },
      { participantId: "maya", text: "I'm thinking a small in person dinner with our top ten design partners on the 13th.", delay: 2000, topic: "event" },
      { participantId: "lena", text: "That's the night before launch. Are we sure we want to be hosting a dinner?", delay: 1800, topic: "event" },
      { participantId: "maya", text: "It's the perfect signal. They feel insider. They post. Free distribution.", delay: 1400, topic: "event" },
      { participantId: "maya", text: "Jon can you confirm the partner list by Monday?", delay: 2000, topic: "event" },
      { participantId: "jon", text: "I can but I'd want us to align on what we're actually telling them first.", delay: 1800, topic: "event" },
      { participantId: "maya", text: "I'll send a draft tonight. Okay I think we're good. Anything else before we wrap?", delay: 1400, topic: "decision" },
      { participantId: "sora", text: "I still want to share the research finding.", delay: 1800, topic: "analytics" },
      { participantId: "maya", text: "Slack me, I'll read it after this. Thanks team.", delay: 1000, topic: "decision" },
    ],
  },
  {
    key: "silent",
    label: "Silent participant",
    pulse: "A voice fades from the room",
    description: "The room seems fine until absence becomes visible.",
    script: [
      { participantId: "jon", text: "Alright agenda for today is the onboarding redesign. Maya wanted us to land on a direction.", delay: 0, topic: "onboarding" },
      { participantId: "maya", text: "Yeah the current flow has a thirty eight percent drop off between sign up and first action. We need to fix it before launch.", delay: 2200, topic: "onboarding" },
      { participantId: "lena", text: "I've sketched two directions. One is a guided checklist, the other is a sample workspace they can play in.", delay: 2000, topic: "onboarding" },
      { participantId: "jon", text: "I lean toward the sample workspace. Less friction.", delay: 1800, topic: "onboarding" },
      { participantId: "maya", text: "Agreed. The checklist feels like a 2018 SaaS pattern.", delay: 1600, topic: "onboarding" },
      { participantId: "lena", text: "Okay so I'll prototype the sample workspace by Wednesday.", delay: 2400, topic: "onboarding" },
      { participantId: "jon", text: "Sounds good. What about the empty state on the dashboard?", delay: 1800, topic: "dashboard" },
      { participantId: "maya", text: "Same approach. Show them a populated example, let them edit.", delay: 1400, topic: "dashboard" },
      { participantId: "lena", text: "I'll cover that in the same prototype.", delay: 1600, topic: "dashboard" },
      { participantId: "jon", text: "Good. Let's also talk about the activation email sequence.", delay: 2200, topic: "email" },
      { participantId: "maya", text: "Three emails over the first week. Day one, day three, day seven. Standard.", delay: 1800, topic: "email" },
      { participantId: "lena", text: "I can put together the templates.", delay: 1400, topic: "email" },
      { participantId: "jon", text: "What's the conversion target on each touchpoint?", delay: 2000, topic: "email" },
      { participantId: "maya", text: "Industry baseline is twenty percent open, eight percent click. We should beat that.", delay: 1800, topic: "email" },
      { participantId: "lena", text: "I'll design them with a single clear CTA each.", delay: 1600, topic: "email" },
      { participantId: "jon", text: "Now the harder question is the in product nudges.", delay: 2200, topic: "tooltips" },
      { participantId: "maya", text: "Tooltips on first hover for the four core actions.", delay: 1400, topic: "tooltips" },
      { participantId: "lena", text: "I'd want them dismissible permanently after first dismiss.", delay: 2000, topic: "tooltips" },
      { participantId: "jon", text: "Agreed. And localized?", delay: 1600, topic: "tooltips" },
      { participantId: "maya", text: "English only for v1. Spanish and French in v1.1.", delay: 1800, topic: "tooltips" },
      { participantId: "lena", text: "Works for me.", delay: 1400, topic: "tooltips" },
      { participantId: "jon", text: "Let's hit pricing transitions next. When users move from free to paid, what's the experience?", delay: 2400, topic: "pricing" },
      { participantId: "maya", text: "Modal at the action that hits the limit. Clear, no dark patterns.", delay: 1800, topic: "pricing" },
      { participantId: "lena", text: "I'll mock it up alongside the workspace prototype.", delay: 1600, topic: "pricing" },
      { participantId: "jon", text: "Great. I think we're aligned then.", delay: 1800, topic: "decision" },
      { participantId: "maya", text: "Yeah let's wrap and circulate notes.", delay: 1200, topic: "decision" },
      { participantId: "jon", text: "One more thing, let's confirm the timeline.", delay: 1600, topic: "timeline" },
      { participantId: "maya", text: "Prototype Wednesday, review Thursday, build starts Monday.", delay: 1400, topic: "timeline" },
      { participantId: "lena", text: "I'll send a calendar invite.", delay: 1600, topic: "timeline" },
    ],
  },
  {
    key: "loop",
    label: "Circular discussion",
    pulse: "The group keeps orbiting the same point",
    description: "A familiar loop appears and the system nudges toward resolution.",
    script: [
      { participantId: "jon", text: "So the question on the table is whether we delay launch by a week.", delay: 0, topic: "delay" },
      { participantId: "maya", text: "I think we have to. The QA backlog is bigger than we thought.", delay: 2000, topic: "delay" },
      { participantId: "sora", text: "But a week pushes us past the marketing window.", delay: 1600, topic: "delay" },
      { participantId: "lena", text: "Could we ship with the known bugs and patch in week two?", delay: 2200, topic: "delay" },
      { participantId: "jon", text: "That depends on which bugs. The auth ones are blockers.", delay: 1800, topic: "delay" },
      { participantId: "maya", text: "Right so we're back to delay or cut scope.", delay: 2000, topic: "delay" },
      { participantId: "sora", text: "I keep coming back to the marketing window. We can't slip past the 21st.", delay: 1800, topic: "delay" },
      { participantId: "lena", text: "What if we cut the workspace feature entirely?", delay: 2200, topic: "delay" },
      { participantId: "jon", text: "That brings us back to what's a v1 must have.", delay: 2000, topic: "delay" },
      { participantId: "maya", text: "And we said the workspace is core. So we're stuck: delay or accept the bugs.", delay: 2400, topic: "delay" },
      { participantId: "sora", text: "But if we delay we miss the window.", delay: 1400, topic: "delay" },
      { participantId: "lena", text: "And if we don't delay we ship something broken.", delay: 1600, topic: "delay" },
      { participantId: "jon", text: "So delay or cut. That's where we keep landing.", delay: 2000, topic: "delay" },
      { participantId: "maya", text: "Yeah I'm not sure how to break this.", delay: 1800, topic: "delay" },
      { participantId: "sora", text: "Maybe we revisit the bug list and see which ones are blockers.", delay: 2400, topic: "delay" },
      { participantId: "jon", text: "We did that on Monday though. The auth ones came up then too.", delay: 2000, topic: "delay" },
      { participantId: "lena", text: "Could we get more eng resources on QA for the next week?", delay: 2200, topic: "delay" },
      { participantId: "maya", text: "From where? Everyone's already pulled in.", delay: 1600, topic: "delay" },
      { participantId: "sora", text: "So no new resources, can't ship broken, can't delay past the 21st.", delay: 1800, topic: "delay" },
      { participantId: "jon", text: "Right, which is the same place we were ten minutes ago.", delay: 2000, topic: "delay" },
      { participantId: "lena", text: "What if marketing pushes the campaign instead?", delay: 2200, topic: "delay" },
      { participantId: "maya", text: "We tried that last sprint. The campaign is locked with the agency.", delay: 1800, topic: "delay" },
      { participantId: "sora", text: "Then we're back to delay or cut.", delay: 1400, topic: "delay" },
      { participantId: "jon", text: "I feel like we keep saying that.", delay: 1800, topic: "delay" },
      { participantId: "lena", text: "Because that's where the constraints leave us.", delay: 1600, topic: "delay" },
      { participantId: "maya", text: "Okay let me try this differently. What if we just look at the auth bugs in isolation?", delay: 2400, topic: "delay" },
      { participantId: "jon", text: "Same conclusion. They're blockers.", delay: 1800, topic: "delay" },
      { participantId: "sora", text: "So we're at delay or cut.", delay: 1600, topic: "delay" },
      { participantId: "lena", text: "Maya, what's your gut?", delay: 1800, topic: "delay" },
      { participantId: "maya", text: "Honestly I don't know. That's why I keep going in circles.", delay: 1600, topic: "delay" },
    ],
  },
];

// Live mode simulation script — played when user clicks "Play simulation" in Live mode
export const liveSimulationScript: DemoStep[] = [
  { type: "message", participantId: "jon", text: "Standup. Quick round, what did you ship yesterday and what's blocking today.", delay: 0, topic: "standup" },
  { type: "message", participantId: "lena", text: "I shipped the new empty states for the dashboard. No blockers.", delay: 1800, topic: "standup" },
  { type: "message", participantId: "sora", text: "I finished the user interviews from last week. Writing up findings today.", delay: 1600, topic: "standup" },
  { type: "message", participantId: "maya", text: "I closed three tickets on the billing flow. Pairing with infra on the rate limiter today.", delay: 1800, topic: "standup" },
  { type: "message", participantId: "jon", text: "Good. Anyone need anything from the group?", delay: 1600, topic: "standup" },
  { type: "message", participantId: "lena", text: "Could use a design review on the empty states later this week.", delay: 1800, topic: "design" },
  { type: "message", participantId: "maya", text: "I'll join. Also wanted to flag, I think we should reconsider the launch date.", delay: 2000, topic: "launch" },
  { type: "message", participantId: "jon", text: "Why what's changed?", delay: 1400, topic: "launch" },
  { type: "message", participantId: "maya", text: "QA found four more issues yesterday. I don't think we make the 14th cleanly.", delay: 1800, topic: "launch" },
  { type: "message", participantId: "maya", text: "And honestly even if we patch them I'm not confident in the overall stability.", delay: 2000, topic: "launch" },
  { type: "message", participantId: "maya", text: "I'd rather push to the 21st and ship something we're proud of.", delay: 1800, topic: "launch" },
  { type: "message", participantId: "lena", text: "What do the issues look like? Are they edge cases or core flow?", delay: 1800, topic: "qa" },
  { type: "message", participantId: "maya", text: "Mix of both. Two are core flow, two are edge cases.", delay: 1600, topic: "qa" },
  { type: "message", participantId: "maya", text: "But the core flow ones touch the auth boundary which makes me nervous.", delay: 1800, topic: "qa" },
  { type: "message", participantId: "maya", text: "I just don't want a repeat of the November incident.", delay: 1600, topic: "qa" },
  { type: "message", participantId: "maya", text: "I'd rather take the heat on a delayed launch than the heat on a broken one.", delay: 1800, topic: "launch" },
  { type: "message", participantId: "jon", text: "What does eng leadership think?", delay: 1600, topic: "launch" },
  { type: "message", participantId: "maya", text: "I haven't talked to them yet. Wanted to align here first.", delay: 1400, topic: "launch" },
  { type: "message", participantId: "maya", text: "But I'm pretty sure they'll back a delay.", delay: 1600, topic: "launch" },
  { type: "message", participantId: "lena", text: "Sora you've been quiet, what do you think?", delay: 2200, topic: "research" },
  { type: "message", participantId: "sora", text: "Honestly I think the core flow issues need a hard look before we decide.", delay: 1800, topic: "research" },
  { type: "message", participantId: "sora", text: "From the interviews I ran last week, users are already at low patience for auth friction.", delay: 2000, topic: "research" },
  { type: "message", participantId: "sora", text: "If launch ships with auth problems we lose trust we won't get back.", delay: 1800, topic: "research" },
  { type: "message", participantId: "jon", text: "That's a really useful point.", delay: 1400, topic: "research" },
  { type: "message", participantId: "maya", text: "Yeah okay. So delay aligns with what the research is telling us too.", delay: 1800, topic: "decision" },
  { type: "message", participantId: "lena", text: "What's the marketing impact of pushing a week?", delay: 1800, topic: "launch" },
  { type: "message", participantId: "maya", text: "I'll need to talk to them. But the 21st is still in the window.", delay: 1600, topic: "launch" },
  { type: "message", participantId: "jon", text: "Okay, action item: Maya talks to marketing and eng leadership today, we revisit tomorrow.", delay: 2400, topic: "decision" },
  { type: "message", participantId: "maya", text: "Works.", delay: 1200, topic: "decision" },
  { type: "message", participantId: "lena", text: "Sounds good.", delay: 1200, topic: "decision" },
  { type: "message", participantId: "sora", text: "Agreed.", delay: 1200, topic: "decision" },
  { type: "message", participantId: "jon", text: "Cool. Wrapping. Good standup everyone.", delay: 1400, topic: "standup" },
];

export const demoSequence: DemoStep[] = [
  { type: "message", participantId: "maya", text: "We need a launch call by Friday.", topic: "launch", delay: 700 },
  { type: "message", participantId: "jon", text: "Infra can make that if scope stays tight.", topic: "launch", delay: 1100 },
  { type: "message", participantId: "lena", text: "The entry flow is close, but onboarding still needs one pass.", topic: "design", delay: 1200 },
  { type: "spotlight", title: "Balanced room", note: "Several voices shape the start.", tone: "signal", delay: 850 },
  { type: "message", participantId: "maya", text: "I still want the date locked now.", topic: "launch", delay: 1200 },
  { type: "message", participantId: "maya", text: "If we wait longer, marketing loses the window.", topic: "launch", delay: 950 },
  { type: "message", participantId: "maya", text: "I need a yes or no today.", topic: "decision", delay: 900 },
  { type: "spotlight", title: "Imbalance forms", note: "One voice starts to compress the room.", tone: "signal", delay: 900 },
  { type: "message", participantId: "jon", text: "We can do it, but that leaves less room for testing.", topic: "risk", delay: 1700 },
  { type: "message", participantId: "sora", text: "Pilot feedback still points to confusion in the first minute.", topic: "evidence", delay: 2200 },
  { type: "spotlight", title: "Gentle intervention", note: "The system invites the missing perspective in.", tone: "balance", delay: 800 },
  { type: "message", participantId: "lena", text: "If we simplify the first-run path, the date feels safer.", topic: "resolution", delay: 1600 },
  { type: "message", participantId: "maya", text: "That works. Lock Friday if the first-run path ships with it.", topic: "decision", delay: 1400 },
  { type: "spotlight", title: "Balance returns", note: "The room widens, then settles.", tone: "balance", delay: 850 },
  { type: "message", participantId: "jon", text: "Engineering can commit to that version.", topic: "decision", delay: 1500 },
  { type: "message", participantId: "sora", text: "Research is aligned if the simpler path is explicit.", topic: "decision", delay: 1350 },
  { type: "spotlight", title: "Clear convergence", note: "Detection, guidance, alignment.", tone: "decision", delay: 900 },
];
